# Generated by Django 5.0.1 on 2025-12-21 04:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
                ('color', models.CharField(default='primary', help_text='primary, blue, green, purple, orange', max_length=20, verbose_name='สี')),
            ],
            options={
                'verbose_name': 'หมวดหมู่ข่าว',
                'verbose_name_plural': 'หมวดหมู่ข่าว',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('title', models.CharField(max_length=300, verbose_name='หัวข้อข่าว')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='เนื้อหาย่อ')),
                ('content', models.TextField(verbose_name='เนื้อหา')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/', verbose_name='รูปภาพประกอบ')),
                ('is_published', models.BooleanField(default=True, verbose_name='เผยแพร่')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ข่าวเด่น')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่เผยแพร่')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='จำนวนเข้าชม')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'ข่าว',
                'verbose_name_plural': 'ข่าวประชาสัมพันธ์',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='news/attachments/%Y/%m/', verbose_name='ไฟล์')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='ชื่อไฟล์')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='news.news', verbose_name='ข่าว')),
            ],
            options={
                'verbose_name': 'ไฟล์แนบ',
                'verbose_name_plural': 'ไฟล์แนบ',
            },
        ),
    ]
