# Generated by Django 5.2.9 on 2025-12-25 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('news', '0003_alter_category_slug_alter_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='gallery',
            field=models.ForeignKey(blank=True, help_text='เลือกอัลบั้มภาพที่เกี่ยวข้องกับข่าวนี้', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='gallery.gallery', verbose_name='อัลบั้มภาพกิจกรรม'),
        ),
    ]
