# Generated by Django 5.0.1 on 2025-12-21 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('title', models.CharField(help_text='เช่น ศ.นพ., รศ.ดร.นพ.', max_length=50, verbose_name='คำนำหน้า')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
                ('position', models.CharField(choices=[('dean', 'คณบดี'), ('vice_dean', 'รองคณบดี'), ('assistant_dean', 'ผู้ช่วยคณบดี'), ('head', 'หัวหน้าภาควิชา'), ('other', 'อื่นๆ')], max_length=20, verbose_name='ประเภทตำแหน่ง')),
                ('position_title', models.CharField(max_length=200, verbose_name='ชื่อตำแหน่ง')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='executives/', verbose_name='รูปภาพ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='โทรศัพท์')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับการแสดง')),
                ('is_active', models.BooleanField(default=True, verbose_name='แสดง')),
            ],
            options={
                'verbose_name': 'ผู้บริหาร',
                'verbose_name_plural': 'ผู้บริหาร',
                'ordering': ['order', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อภาควิชา')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='ชื่อภาษาอังกฤษ')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='โทรศัพท์')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับการแสดง')),
                ('is_active', models.BooleanField(default=True, verbose_name='แสดง')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.executive', verbose_name='หัวหน้าภาควิชา')),
            ],
            options={
                'verbose_name': 'ภาควิชา',
                'verbose_name_plural': 'ภาควิชา/หน่วยงาน',
                'ordering': ['order', 'name'],
            },
        ),
    ]
