# Generated by Django 5.2.9 on 2025-12-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('preclinical', 'พรีคลินิก'), ('clinical', 'คลินิก'), ('thai_medicine', 'แพทย์แผนไทย'), ('support', 'สนับสนุน')], default='clinical', max_length=20, verbose_name='ประเภทภาควิชา'),
        ),
    ]
