# Generated by Django 5.2.9 on 2025-12-29 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_department_department_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('title', models.CharField(help_text='เช่น ดร., อ., ผศ.ดร.', max_length=50, verbose_name='คำนำหน้า')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
                ('personnel_type', models.CharField(choices=[('preclinical', 'พรีคลินิก'), ('clinical', 'คลินิก'), ('thai_medicine', 'แพทย์แผนไทย'), ('supporting_staff', 'สายสนับสนุน')], default='clinical', max_length=20, verbose_name='ประเภทบุคลากร')),
                ('position', models.CharField(max_length=200, verbose_name='ตำแหน่ง')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='ความเชี่ยวชาญ')),
                ('education', models.TextField(blank=True, verbose_name='วุฒิการศึกษา')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personnel/', verbose_name='รูปภาพ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='โทรศัพท์')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับการแสดง')),
                ('is_active', models.BooleanField(default=True, verbose_name='แสดง')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.department', verbose_name='ภาควิชา')),
            ],
            options={
                'verbose_name': 'บุคลากร',
                'verbose_name_plural': 'บุคลากร',
                'ordering': ['personnel_type', 'order', 'first_name'],
            },
        ),
    ]
