# Generated by Django 5.2.9 on 2025-12-30 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อหน้าที่')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับการแสดง')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
            ],
            options={
                'verbose_name': 'หน้าที่ความรับผิดชอบ',
                'verbose_name_plural': 'หน้าที่ความรับผิดชอบ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='personnel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.department', verbose_name='ภาควิชา/ฝ่าย'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='responsibilities',
            field=models.ManyToManyField(blank=True, to='about.responsibility', verbose_name='ปฏิบัติหน้าที่'),
        ),
    ]
