# Generated by Django 5.0.1 on 2025-12-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='คณะแพทยศาสตร์', max_length=200, verbose_name='ชื่อเว็บไซต์')),
                ('site_description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='โทรศัพท์')),
                ('contact_address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('line_id', models.CharField(blank=True, max_length=50, verbose_name='Line ID')),
            ],
            options={
                'verbose_name': 'ตั้งค่าเว็บไซต์',
                'verbose_name_plural': 'ตั้งค่าเว็บไซต์',
            },
        ),
    ]
