# Generated by Django 5.2.9 on 2025-12-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/', verbose_name='รูปภาพ')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='ข้อความปุ่ม')),
                ('button_link', models.CharField(blank=True, help_text='URL เช่น /education/admission/ หรือ https://example.com', max_length=500, verbose_name='ลิงก์ปุ่ม')),
                ('order', models.IntegerField(default=0, help_text='เลขน้อยแสดงก่อน', verbose_name='ลำดับการแสดง')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่เริ่มแสดง')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่สิ้นสุด')),
            ],
            options={
                'verbose_name': 'แบนเนอร์',
                'verbose_name_plural': 'แบนเนอร์',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
