# Generated by Django 5.2.9 on 2025-12-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_banner',
            field=models.BooleanField(default=False, help_text='เปิดเพื่อแสดง Carousel Banner / ปิดเพื่อแสดง Hero Section แบบเดิม', verbose_name='เปิดใช้งานแบนเนอร์'),
        ),
    ]
