# Generated by Django 5.2.9 on 2025-12-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_enable_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button1_link',
            field=models.CharField(blank=True, default='/education/admission/', max_length=500, verbose_name='ปุ่มที่ 1 - ลิงก์'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button1_text',
            field=models.CharField(blank=True, default='รับสมัครนักศึกษา', max_length=100, verbose_name='ปุ่มที่ 1 - ข้อความ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button2_link',
            field=models.CharField(blank=True, default='/about/', max_length=500, verbose_name='ปุ่มที่ 2 - ลิงก์'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button2_text',
            field=models.CharField(blank=True, default='เรียนรู้เพิ่มเติม', max_length=100, verbose_name='ปุ่มที่ 2 - ข้อความ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_description',
            field=models.TextField(blank=True, default='มุ่งมั่นผลิตแพทย์ที่มีคุณภาพ เพื่อรับใช้สังคมและชุมชน', verbose_name='คำอธิบาย'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(blank=True, default='มหาวิทยาลัยนครพนม', max_length=200, verbose_name='หัวข้อย่อย'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_tag_line',
            field=models.CharField(blank=True, default='🏥 ผลิตแพทย์เพื่อชุมชนอีสาน', max_length=200, verbose_name='Tag Line'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(blank=True, default='คณะแพทยศาสตร์', max_length=200, verbose_name='หัวข้อหลัก'),
        ),
    ]
