# Generated by Django 5.2.9 on 2025-12-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_hero_button1_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('image', models.ImageField(help_text='แนะนำขนาด 800x600 พิกเซล', upload_to='popups/%Y/%m/', verbose_name='รูปภาพ')),
                ('link_url', models.CharField(blank=True, help_text='URL เช่น /education/admission/ หรือ https://example.com', max_length=500, verbose_name='ลิงก์')),
                ('link_text', models.CharField(blank=True, default='คลิกเพื่อดูรายละเอียด', max_length=100, verbose_name='ข้อความลิงก์')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่เริ่มแสดง')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่สิ้นสุด')),
                ('auto_close_delay', models.IntegerField(default=0, help_text='0 = ไม่ปิดอัตโนมัติ, ต้องกดปิดเอง', verbose_name='ปิดอัตโนมัติหลังจาก (วินาที)')),
                ('show_frequency', models.CharField(choices=[('always', 'แสดงทุกครั้ง'), ('once_per_session', 'แสดงครั้งเดียวต่อ Session'), ('once_per_day', 'แสดงครั้งเดียวต่อวัน'), ('once_forever', 'แสดงครั้งเดียวตลอดกาล')], default='once_per_session', max_length=20, verbose_name='ความถี่การแสดง')),
                ('show_delay', models.IntegerField(default=2, help_text='เวลารอก่อนแสดง Popup (0-10 วินาที)', verbose_name='หน่วงเวลาก่อนแสดง (วินาที)')),
                ('size', models.CharField(choices=[('small', 'เล็ก (400x300)'), ('medium', 'กลาง (600x450)'), ('large', 'ใหญ่ (800x600)')], default='medium', max_length=10, verbose_name='ขนาด')),
                ('view_count', models.IntegerField(default=0, editable=False, verbose_name='จำนวนครั้งที่แสดง')),
                ('click_count', models.IntegerField(default=0, editable=False, verbose_name='จำนวนครั้งที่คลิก')),
            ],
            options={
                'verbose_name': 'Popup',
                'verbose_name_plural': 'Popup',
                'ordering': ['-created_at'],
            },
        ),
    ]
