# Generated by Django 5.2.9 on 2025-12-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_popup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='image',
            field=models.ImageField(help_text='แนะนำขนาด 800x450 พิกเซล (16:9)', upload_to='popups/%Y/%m/', verbose_name='รูปภาพ'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='size',
            field=models.CharField(choices=[('small', 'เล็ก (640x360) 16:9'), ('medium', 'กลาง (800x450) 16:9'), ('large', 'ใหญ่ (1280x720) 16:9')], default='medium', max_length=10, verbose_name='ขนาด'),
        ),
    ]
