# Generated by Django 5.2.9 on 2025-12-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_popup_image_alter_popup_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_embed',
            field=models.TextField(blank=True, help_text='ใส่ iframe embed code จาก Google Maps (แชร์ > ฝังแผนที่)', verbose_name='Google Maps Embed Code'),
        ),
    ]
