# Generated by Django 5.2.9 on 2025-12-25 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่ออัลบั้ม')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('cover_image', models.ImageField(blank=True, help_text='รูปปกของอัลบั้ม (แนะนำขนาด 1200x800 px)', null=True, upload_to='gallery/covers/%Y/%m/', verbose_name='รูปปก')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='วันที่จัดกิจกรรม')),
                ('is_published', models.BooleanField(default=True, verbose_name='เผยแพร่')),
                ('order', models.IntegerField(default=0, verbose_name='ลำดับการแสดงผล')),
            ],
            options={
                'verbose_name': 'อัลบั้มภาพ',
                'verbose_name_plural': 'อัลบั้มภาพกิจกรรม',
                'ordering': ['-order', '-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/images/%Y/%m/', verbose_name='รูปภาพต้นฉบับ')),
                ('thumbnail', models.ImageField(blank=True, upload_to='gallery/thumbnails/%Y/%m/', verbose_name='รูปย่อ')),
                ('medium', models.ImageField(blank=True, upload_to='gallery/medium/%Y/%m/', verbose_name='รูปขนาดกลาง')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='คำบรรยาย')),
                ('order', models.IntegerField(default=0, verbose_name='ลำดับ')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.gallery', verbose_name='อัลบั้ม')),
            ],
            options={
                'verbose_name': 'รูปภาพ',
                'verbose_name_plural': 'รูปภาพในอัลบั้ม',
                'ordering': ['order', 'id'],
            },
        ),
    ]
