# Generated by Django 5.0.1 on 2025-12-21 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('name', models.CharField(max_length=300, verbose_name='ชื่อหลักสูตร')),
                ('name_en', models.CharField(blank=True, max_length=300, verbose_name='ชื่อภาษาอังกฤษ')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
                ('level', models.CharField(choices=[('bachelor', 'ปริญญาตรี'), ('master', 'ปริญญาโท'), ('doctoral', 'ปริญญาเอก'), ('diploma', 'ประกาศนียบัตร')], max_length=20, verbose_name='ระดับ')),
                ('degree', models.CharField(help_text='เช่น พ.บ., วท.ม.', max_length=100, verbose_name='ชื่อปริญญา')),
                ('degree_en', models.CharField(blank=True, help_text='เช่น M.D., M.Sc.', max_length=100, verbose_name='ชื่อปริญญาภาษาอังกฤษ')),
                ('duration', models.CharField(help_text='เช่น 6 ปี', max_length=50, verbose_name='ระยะเวลาเรียน')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('curriculum_file', models.FileField(blank=True, null=True, upload_to='education/programs/', verbose_name='ไฟล์หลักสูตร (PDF)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='education/programs/', verbose_name='รูปภาพ')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดสอน')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับการแสดง')),
            ],
            options={
                'verbose_name': 'หลักสูตร',
                'verbose_name_plural': 'หลักสูตร',
                'ordering': ['order', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
                ('title', models.CharField(max_length=300, verbose_name='หัวข้อ')),
                ('academic_year', models.CharField(help_text='เช่น 2568', max_length=10, verbose_name='ปีการศึกษา')),
                ('round_name', models.CharField(help_text='เช่น Portfolio, Quota, Admission', max_length=100, verbose_name='รอบการรับสมัคร')),
                ('start_date', models.DateField(verbose_name='วันเริ่มรับสมัคร')),
                ('end_date', models.DateField(verbose_name='วันสิ้นสุดรับสมัคร')),
                ('quota', models.PositiveIntegerField(default=0, verbose_name='จำนวนรับ')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('requirements', models.TextField(blank=True, verbose_name='คุณสมบัติผู้สมัคร')),
                ('announcement_file', models.FileField(blank=True, null=True, upload_to='education/admissions/', verbose_name='ไฟล์ประกาศ')),
                ('apply_url', models.URLField(blank=True, verbose_name='ลิงก์สมัคร')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดรับสมัคร')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.program', verbose_name='หลักสูตร')),
            ],
            options={
                'verbose_name': 'ประกาศรับสมัคร',
                'verbose_name_plural': 'ประกาศรับสมัคร',
                'ordering': ['-academic_year', '-start_date'],
            },
        ),
    ]
